Simple healthcheck
WebOfTrust/keria pull request #144
Opened 2023-12-07 20:38 UTC by kentbull

Adds a simple healthcheck endpoint at each of the ports that is allowed through the SignifyTS header check. 

This is not a fully involved healthcheck that has useful statistics on the Agency, Habery, or Habs. That would be cool and will happen in a future evolution of the healthcheck. This endpoint is just to support a simple runtime status reporting that the application is running.

This is useful for Kubernetes readinessProbes and livenessProbes.

2023-12-08 14:27 UTC, pfeairheller requested changes
I don't like exposing another un-authed endpoint for Agents.  In addition I don't think its needed as you can just use the get on state to see if an agent is awake.  Please remove this from the agent port and we can merge it just for Boot.

2023-12-19 18:48 UTC, pfeairheller requested changes
Sorry for the delay getting back to this, but could you remove the route registrations.

2023-12-19 18:48 UTC, pfeairheller commented on src/keria/app/agenting.py
> +    app.add_route("/health", HealthEnd())
Please remove this route registration

2023-12-19 18:48 UTC, pfeairheller commented on src/keria/app/agenting.py
> +        happ.add_route("/health", HealthEnd())
Please remove this route registation

2023-12-19 18:55 UTC, kentbull commented on src/keria/app/agenting.py
> +    app.add_route("/health", HealthEnd())
done

2023-12-19 18:55 UTC, kentbull commented on src/keria/app/agenting.py
> +        happ.add_route("/health", HealthEnd())
done

2023-12-19 18:58 UTC, kentbull commented
Made all changes and then rebased on latest development, which I should'nt have. Now there's a failing test, `test_identifier_collection_end` in test_aiding` to unrelated functionality, when I run `pytest` locally.

Error message:
```python
            # Test Group Multisig
            keys = [signer0.verfer.qb64, p1.kever.verfers[0].qb64, p2.kever.verfers[0].qb64, ]
>           ndigs = [diger0.qb64, p1.kever.ndigers[0].qb64, p2.kever.ndigers[0].qb64]
E           AttributeError: 'Kever' object has no attribute 'ndigers'
```

2023-12-19 18:58 UTC, m00sey approved these changes

2023-12-19 19:02 UTC, pfeairheller commented
> Made all changes and then rebased on latest development, which I shouldn't have. Now there's a failing test, `test_identifier_collection_end` in test_aiding`to unrelated functionality, when I run`pytest` locally.
> 
> Error message:
> 
> ```python
>             # Test Group Multisig
>             keys = [signer0.verfer.qb64, p1.kever.verfers[0].qb64, p2.kever.verfers[0].qb64, ]
> >           ndigs = [diger0.qb64, p1.kever.ndigers[0].qb64, p2.kever.ndigers[0].qb64]
> E           AttributeError: 'Kever' object has no attribute 'ndigers'
> ```

You need to update your local environment to the latest KERIpy development branch

2023-12-19 19:03 UTC, pfeairheller approved these changes

2023-12-19 19:03 UTC, merged