Fix/del rot smid rmid tests
WebOfTrust/keria pull request #254
Opened 2024-06-13 15:01 UTC by 2byrds

Catches KERIA up with KERIpy changes AND provides all functionality necessary for SIGNIFY-TS integration tests to pass, especially multisig-vlei-issuance but also fixes for rotation, salty, and delegation

2024-06-14 14:21 UTC, m00sey commented on src/keria/app/delegating.py
> +        Process escrow of unacnchored events that have been delegated and are waiting for delegator anchor/approval.
duplicated comment?

2024-06-20 14:43 UTC, 2byrds commented
There is a small amount of overlap with https://github.com/WebOfTrust/signify-ts/pull/234/files but we'll adjust once either is merged.

2024-06-20 19:12 UTC, pfeairheller requested changes

2024-06-20 19:12 UTC, pfeairheller commented on src/keria/app/aiding.py
> +                # smids = [state['i'] for state in states]
Please delete this code if its no longer needed.

2024-06-20 19:12 UTC, pfeairheller commented on src/keria/app/delegating.py
> +@staticmethod
If this method is no longer a part of the class, this annotation is inappropriate

2024-06-20 19:12 UTC, pfeairheller commented on src/keria/app/aiding.py
> +                smid = smid['i']
Are there really cases where the contents of smids could be either a dict or a str?  We should figure out why and if that's necessary

2024-06-20 19:12 UTC, pfeairheller commented on src/keria/app/aiding.py
> +            if isinstance(rmid,dict):
Same as above

2024-06-22 00:38 UTC, 2byrds commented
@pfeairheller I have made all the updates based on your review. I also added a small change to grouping.py to address @daviddm [issue](https://github.com/WebOfTrust/signify-ts/issues/227) and corresponding PR which contains an additional signify-ts test (https://github.com/WebOfTrust/signify-ts/pull/258) that will now pass and can be merged after this.

I also ran against all original singify-ts integration tests again:
![image](https://github.com/WebOfTrust/keria/assets/681493/e5c0da18-2a70-45e0-93c7-884eb401dfaf)

2024-06-22 02:18 UTC, pfeairheller approved these changes

2024-06-22 02:20 UTC, merged